### PR TITLE
Correct `setup.sh`adding path to `PATH`

### PR DESCRIPTION
**Pull request by joaomcteixeira**

### CODE REVIEW

**Comment by DaniBodor** [comment]
is there a reason this is preferred over my solution in PR #3 ?

**Comment by joaomcteixeira** [comment]
Hi Dani,

Let me just clarify I pushed this PR without realizing the modifications in #3.  Nonetheless, these are the benefits I see for using `setup.sh` instead of the strategy currently in #3 :

1. it ensures there are no copy+paste errors from copying the command from the `README` and pasting to the terminal
2. we can safely add more instructions to `setup.sh` in the future without modifying the installation instructions, as the same general command would apply `source setup.sh`.

Please let me know what your thoughts are.
Cheers!

**Comment by DaniBodor** [comment]
Either way is fine. Feel free to merge it the way you prefer and then close or adjust the other one.

**Review by DaniBodor — APPROVED** [review]

**Comment by joaomcteixeira** [comment]
Closed by #6

**Pull request closed without merging**
